# Change these first
owner: a1exalexander # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Merge (Our Team Website)
    url: https://www.merge.rocks/
  - name: Noviscient (Investment Management)
    url: https://portal.noviscient.com/
  - name: Tokenplace (Trading Terminal)
    url: https://app.tokenplace.com/
  - name: School 23
    url: https://school23.now.sh/
  - name: Exchanger (UAH currency converter)
    url: https://exchanger.now.sh/
  - name: Stay At Home (Self Isolation Todo)
    url: https://self-isolation.now.sh/
  - name: Tic Tac Toe (PvP Game)
    url: https://tic-tac.vercel.app/
  - name: Media Scout (Demo - Youtube manager)
    url: https://media-scout.netlify.app/
  - name: Merge Coworking (Demo)
    url: https://a1exalexander.github.io/merge-draft/dist/
  - name: Cloudbeat (Demo - Dashboard)
    url: https://cloudbeat.now.sh/
  - name: Biofunder (Demo - Investment Manager)
    url: https://forcewizu.bitbucket.io/biofunder
  - name: Biofunder (Demo - Back-office)
    url: https://a1exalexander.github.io/riseeds-admin/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
